### PR TITLE
fix: Strike match

### PR DESCRIPTION
**Pull request by kozer**
I am working on a case, where the output of match is not what I expected.

~Some text
Multi line ~
single ~~line~~

This is the output of slack, however when I use the library I get:
~~Some text
   Multi line~~
single ~~line~~

This pr fix this issue.

### CODE REVIEW

**Review by danielbachhuber — COMMENTED** [review]
@kozer Can you include a bit more detail in your description as to _how_ this pull request fixes the issue? What are the ways in which strike will deviate from strong? Is this difference present in Slack messages too?

**Comment by Sorunome** [comment]
Could you please confirm if this is actually part of slack mrkdwn and not just something due to their undocumented blocks? Sending in the web client is *not* enough for that, as that just gets converted to the undocumented blocks

**Comment by kozer** [comment]
> Could you please confirm if this is actually part of slack mrkdwn and not just something due to their undocumented blocks? Sending in the web client is not enough for that, as that just gets converted to the undocumented blocks

Can you give me some context about the "undocumented blocks" and what's the difference between that and slack mrkdwn? I have no idea tbh. 

What I did was compare a message in the slack app (linux client) with what this library produced.

**Comment by Sorunome** [comment]
Then it is likely the undocumented blocks. Basically, the official slack clients do a lot more complex parsing client-sided and send them in an abstract syntax tree attached to the message, in an object called `blocks` (in the message payload received from the server). If the `blocks` is present, slack displays that instead of the mrkdwn. And, well, this library is for the mrkdwn only, however Soru is working on one that does those blocks, too.

Oh, and why undocumented? Because, well, for the normal formatting blocks there is no documentation to find anywhere, but soru reverse-engineered them some time ago :3

**Comment by danielbachhuber** [comment]
Thanks for the feedback, @Sorunome ! That sounds reasonable 😊

**Pull request closed without merging**
