### PR TITLE
TypeScript support

### PR DESCRIPTION
**Pull request by ramtinsoltani**
This PR adds `index.d.ts` TypeScript declaration file with TypeDoc comments (taken from the README).

### CODE REVIEW

**Comment by ramtinsoltani** [comment]
@Sorunome This is ready for review 😄

**Comment by ramtinsoltani** [comment]
@pencil @Sorunome Any ideas if/when this PR will be merged and released? Our company wants to depend on this package (as we find it the best suitable solution for rendering Slack-flavored markdown) but really need the TypeScript compatibility.

**Comment by pencil** [comment]
I'm not a maintainer of this repository.

**Comment by Sorunome** [comment]
Totally forgot about this, sorry!

**Comment by Sorunome** [comment]
should be published at 0.2.0 now, thank you!

**Pull request merged**
